name: Update data

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # run once a month

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -e . --no-deps
          pip install --require-hashes -r requirements-lock.txt
          pip install --require-hashes -r requirements-data-lock.txt
          pip install --require-hashes -r requirements-test-lock.txt

      - name: Update data
        run: |
          python scripts/updatedata.py

      - name: Run pre-commit
        continue-on-error: true
        run: |
          pre-commit run --files src/codicefiscale/data/countries.json src/codicefiscale/data/municipalities.json

      - name: Commit data
        uses: test-room-7/action-update-file@be6fb6d9c59d5ec4b56542f2e8ad2516a99e3402 # v2.0.0
        with:
          file-path: |
            src/codicefiscale/data/countries.json
            src/codicefiscale/data/municipalities.json
          commit-msg: "Updated `countries.json` and/or `municipalities.json` data."
          committer-name: "Fabio Caccamo [bot]"
          committer-email: "fabio.caccamo@gmail.com"
          github-token: ${{ secrets.WORKFLOWS_UPDATE_DATA_TOKEN }}
